meson: compile with -fsigned-char
Currently, libcper currently fails to compile on my machine (GCC 13):

    ../cper-utils.c: In function ‘add_untrusted_string’:
    ../cper-utils.c:467:23: error: comparison is always false due to
    limited range of data type [-Werror=type-limits]
      467 |                 if (c < 0) {
          |                       ^

The reason seems to be that char signedness is implementation-defined,
we have to explicitly use unsigned char or signed char to get a portable
char type. In our case, char is unsigned char, hence the warning.

I think it is fair to assume that libcper was written with signed char
in mind (hence all the c < 0 checks), so turning on -fsigned-char should
reflect the current state of the codebase better.

Whether we want to exhaustively explicitly change everything to signed
char or use uint8_t/int8_t can go into another change or discussion.

Tested: compilation successfully

Change-Id: I98c7c10a674c8817e0b2cbe82c26f6590d8d716a
Signed-off-by: Khang D Nguyen <khangng@os.amperecomputing.com>