Fix base64 decode_table size
Array size is 257 due to additional null terminator.

   base64.c:75:9: error: initializer-string for array of
   'unsigned char' truncates NUL terminator but destination
   lacks 'nonstring' attribute (257 chars into 256 available)
   [-Werror=unterminated-string-initialization]

Fix this by initialize it with a proper byte array.

Change-Id: I6a6a6964601f5ae97b4b2c82f16470890da55e07
Signed-off-by: Khang D Nguyen <khangng@os.amperecomputing.com>
Signed-off-by: Ed Tanous <etanous@nvidia.com>