Replace ASCII range checks with isprint()
Currently, libcper currently fails to compile on my machine (GCC 13):

    ../cper-utils.c: In function ‘add_untrusted_string’:
    ../cper-utils.c:467:23: error: comparison is always false due to
    limited range of data type [-Werror=type-limits]
      467 |                 if (c < 0) {
          |                       ^

The reason seems to be that char signedness is implementation-defined,
we have to explicitly use unsigned char or signed char to get a portable
char type. In our case, char is unsigned char, hence the warning.

Apparently we are trying to validate ASCII strings from the records.
Those strings seem to be used for display purpose only, so I think
checking for only printable characters is appropriate.

This changes the range checks to a more precise isprint() check,
which only allow printable ASCII characters, and does not care about the
signedness of char.

Tested: compilation successfully

Change-Id: I98c7c10a674c8817e0b2cbe82c26f6590d8d716a
Signed-off-by: Khang D Nguyen <khangng@os.amperecomputing.com>